### ISSUE TITLE
Functions that need to be completed

### ISSUE THREAD

**Issue by youngboiCoder** [youngboiCoder/Quan-Li-Hoc-Sinh#1]
**Functions that need to be completed including:**

- [x] Searching function: Type in "Search entry" then return data from the table. Recommend creating another screen includes the data searched from the table, using another table.

- [x] Clear function

1. For the easiest way, create a function that deletes all  the data from table
2. For the harder way, create a function that deletes all the selected data from table

- [x] Create the function to type in file's name for exporting csv files (those can be overwritten so this need to be improved). Recommend creating another screen and an entry an saved it as a variable.

![Screenshot 2021-11-29 111935](https://user-images.githubusercontent.com/44545000/143808449-815041e4-e708-4db6-8b59-bdf2335c4b0c.png)

**Comment by ROGKhoa** [comment]
@quangngonz Have any suggestions?
